
version: '3.1'

services:
    roam:
        build:
            context: .
            args:
                env: production
        restart: always
        # volumes:
        #     - ./dist/ROAM:/usr/share/nginx/html
        ports:
            - 8080:80